- .prettierrc
- package-lock.json
- package.json
> 작업한 내용에 대해 자세히 설명해 주세요.
- prettier 설정에 import order 규칙 추가
- React, Next.js, 외부 라이브러리, shared, 상대 경로 순으로 정렬되도록 구성
- @trivago/prettier-plugin-sort-imports 플러그인 설치
- 정렬 순서에 대한 의견 있으시면 남겨주세요!
> [Settings] import 정렬 순서 규칙 설정

- next.config.mjs
nextjs에서 ```GET:  /api/ 어쩌구```로 요청을 보낼 시에 api 요청과 페이지 요청이 충돌하여 문제가 생깁니다.
이를 해결하고자 next.config 파일을 수정하고, .env 파일를 통해 host룰 돌려줄  수 있도록 설정했습니다.
개발 환경에서는 .env.development.local에 다음을 추가합니다.
```
API_HOST=http://localhost:8080
```
실 api 주소가 나오면 실주소로 .env 파일을 업데이트하면 될 것 같습니다.
```/api
```js
// next.config.mjs
+  async rewrites() {
return [
{
// source로 들어오는 요청을 destination주소로 돌려줌
source: '/api/:path*',
destination: `${process.env.API_HOST}/api/:path*`,
},
]
},
```
[참고문서 next.js rewirte](https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites)
> [settings] api 요청시 경로 rewriter 설정

- app/(landing)/signup/_stores/use-signup-store.ts
- app/(landing)/signup/_ui/step/styles.module.scss
- app/(landing)/signup/_ui/user-type-card/index.tsx
- app/(landing)/signup/_ui/user-type-card/styles.module.scss
- app/(landing)/signup/user-type/page.module.scss
- app/(landing)/signup/user-type/page.tsx
- shared/styles/global.scss
- shared/types/user.ts
회원가입 유형 선택 페이지 작업했습니다!
- 회원가입 유형 선택 페이지 퍼블리싱
- 선택한 유형을 저장할 store 추가
기존 디자인에는 다음 버튼이 있었는데, 유형을 선택했을때 바로 다음으로 넘어가는게 나을 것 같아서 디자이너님과 상의 후 버튼을 빼기로 결정했습니다!
- 웹 접근성 향상을 위해 사용되는 `.visually-hidden` 클래스를 global 스타일에 추가해뒀습니다
- 회원 유형, 약관 동의 여부를 저장해둘 필요가 있다는 생각이 들어서 store을 추가했는데 혹시 다른 좋은 방법이 있다면 코멘트 남겨주세요!
- /signup/user-type 경로에서 확인!
> [Feat] 회원가입 유형 선택 페이지

- app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/details-side-item.stories.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/index.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/side-item.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/details-side-item/styles.module.scss
- app/(dashboard)/strategies/[strategyId]/page.tsx
전략상세 사이드정보 아이템 컴포넌트, 스토리북 추가
- 전략상세 사이드정보 아이템 컴포넌트
- 스토리북 추가
> [Feat] 전략상세 사이드정보 아이템 컴포넌트, 스토리북 추가

- app/(landing)/(home)/_ui/hero-section/index.tsx
- app/(landing)/(home)/_ui/hero-section/styles.module.scss
- app/(landing)/(home)/_ui/home-subtitle/index.tsx
- app/(landing)/(home)/_ui/home-subtitle/styles.module.scss
- app/(landing)/(home)/_ui/metric-card/index.tsx
- app/(landing)/(home)/_ui/metric-card/styles.module.scss
- app/(landing)/(home)/_ui/user-metrics-section/index.tsx
- app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
- app/(landing)/(home)/page.tsx
- next.config.mjs
- shared/ui/logo/styles.module.scss
- shared/ui/side-navigation/styles.module.scss
랜딩 페이지 Hero, UserMetrics 섹션 퍼블리싱 작업 했습니다!
원래 MSW까지 설정해서 올리려고 했는데 axios 설치 등.. 혹시모를 충돌 대비해서 일단 퍼블리싱 먼저 올립니다
퍼블리싱도 페이지 전체 진행한 후 올리려다가 Top 랭킹 섹션과 SM Score 섹션 컴포넌트 수정하면 변경사항이 너무 많아지고 복잡해질 것 같아서
Hero, UserMetrics 섹션까지만 PR 올렸습니다!
- svgr 설정 추가
- 아이콘 사이즈 변경하려면 svg 파일에서 width, height를 지우는 등 번거로운 작업이 필요해서 설정을 추가해 해결했습니다
- 🚨🚨아이콘 사용하실때 사이즈 지정 필수🚨🚨
- 헤더는 해석님이 로그인 페이지에서 적용해두셨다고 하셔서 따로 추가 안했습니다!
> [Feat] 랜딩 페이지 Hero, UserMetrics 섹션 퍼블리싱

- shared/ui/traders-list-card/index.tsx
- shared/ui/traders-list-card/styles.module.scss
- shared/ui/traders-list-card/traders-list-card.stories.tsx
트레이더 목록 페이지에 들어가는 **트레이더 리스트 카드 컴포넌트**를 구현했습니다.
> **LinkButton 색상 설정 문제:** LinkButton의 텍스트 색상이 `color:$color-orange-600 `변수가 적용되지 않아 style을 사용해 색상을 직접 지정했습니다. 혹시 해결 방법에 대해 아신다면 조언 부탁드립니다. 
그리고 컴포넌트 구조나 Props 설계에 대한 추가 피드백이 있다면 말씀해 주세요!
_(커밋 단위 좀 더 세분화했어야 했는데 그러지 못한 점 사과드립니다..)_
디자인 변경사항(버튼색상과 nickname 폰트크기 16px으로 변경)과 코드리뷰 반영해서 수정했습니다!
> [Feat] 트레이더 리스트 카드 컴포넌트 구현

- shared/ui/traders-list-card/index.tsx
- shared/ui/traders-list-card/styles.module.scss
- shared/ui/traders-list-card/traders-list-card.stories.tsx
트레이더 리스트 카드 컴포넌트 코드를 변경하고 SCSS를 수정했습니다.
기존에 컴포넌트 내부에 하드코딩되어 있던 링크 버튼을 props로 제어할 수 있도록 수정했습니다.
`hasLinkButton?: boolean` 속성을 추가하여 **링크 버튼의 표시 여부를 결정하도록 변경**했습니다.
기존에는 컴포넌트에 버튼이 고정되어 있었으나, `boolean`을 활용해 필요 시 표시하거나 생략할 수 있게 되었습니다.
추후 확장성을 고려하여 `children `속성을 사용하는 것도 고민했으나, 현재 디자인 상 해당 컴포넌트가 사용되는 페이지가 두 곳으로 한정적이기에 `boolean`으로 구현했습니다.
**장점:** `children`사용시 유연성이 커져 다양한 UI를 삽입 가능
**단점:** 부모 컴포넌트에서 사용하는 사람이 `children`으로 무엇을 넣어야 할지 명확하지 않아 오용 가능성이 생길 수 있음
현재 컴포넌트가 사용되는 곳이 제한적이고, 추가적인 유연성이 불필요한 상황이라 `boolean` 방식이 적합하다고 판단했습니다. 만약 컴포넌트 사용이 증가하거나 버튼 이외의 요소 추가가 요구된다면, `children`으로 변경하는 방안을 다시 검토하겠습니다😊
> [Refactor] 트레이더 리스트 카드 컴포넌트 코드 수정

- shared/styles/base/_variables.scss
- shared/ui/dropdown/index.tsx
- shared/ui/dropdown/styles.module.scss
- shared/ui/dropdown/types.ts
1. option의 position을 absolute로 주지 않아서 option이 열렸을 때 전체적인 레이아웃이 밀리는 버그를 해결했습니다.
2. isMultiple이 필수 옵션으로 지정되어있던 버그 해결했습니다.
3. select의 우측 아이콘 크기를 지정해주었습니다.
> [fix] select 컴포넌트 option이 레이아웃에 영향을 끼치는 버그 수정 및 편의성 개선

- shared/ui/error-messages/error-messages.stories.tsx
- shared/ui/error-messages/index.tsx
- shared/ui/error-messages/styles.module.scss
- shared/ui/input/index.tsx
- shared/ui/input/input.stories.tsx
- shared/ui/input/styles.module.scss
- shared/ui/search-input/index.tsx
기존 `Input`컴포넌트 내부에 포함되어 있던 에러 메시지 로직 `ErrorMessages` 컴포넌트 분리
`Input` 컴포넌트에 `ref` 속성을 적용하여 외부에서 DOM 요소에 직접 접근할 수 있도록 기능 확장
`ErrorMessages` 컴포넌트 분리
`Input` 컴포넌트 개선: `React.forwardRef`를 사용하여 `ref` 속성을 지원.
기존 `ComponentProps`를 `ComponentPropsWithoutRef<'input'>`로 변경하여 기본 <input> 속성을 포함시켰습니다.
장점으로는
1. 자동으로 props 타입 가져오기:
<input> 태그에서 기본적으로 지원하는 props(예: value, onChange, type, placeholder 등)를 일일이 정의하지 않아도 됩니다.
ComponentPropsWithoutRef<'input'>를 사용하면 이런 props를 자동으로 타입으로 설정합니다.
2. ref와의 충돌 방지: 
ref는 리액트 컴포넌트에서 특별히 처리해야 합니다.
ComponentPropsWithoutRef<'input'>는 기본 props에서 ref를 제외하므로, forwardRef와 함께 사용할 때 타입 충돌을 방지할 수 있습니다.
라고 하는데 ref 속성 적용은 이번이 두 번째라 많이 부족합니다.. 불필요한 코드가 있을 시 말씀해 주시면 감사하겠습니다.
```ts
// Input ref 속성 활용 예시
import { useRef } from 'react';
import { Input } from './Input';
const …
```
> [Feat] Input 에러메시지 컴포넌트 분리 및 ref속성 추가

- app/(dashboard)/traders/[traderId]/page.module.scss
- app/(dashboard)/traders/[traderId]/page.tsx
**1. 트레이더 상세보기 페이지 레이아웃 구현**
`BackHeader`를 사용하여 상단에 '목록으로 돌아가기' 버튼 추가.
페이지 타이틀은 `Title`컴포넌트를 활용해 '트레이더 상세보기'로 표시.
트레이더 정보를 표시하기 위해 `TradersListCard` 컴포넌트 렌더링.
**2. 전략 정보 리스트**
`ListHeader`를 추가하여 전략 목록 상단에 헤더 구성.
더미 데이터를 기반으로 `StrategiesItem` 컴포넌트를 3회 반복 렌더링.
**3. 임시 데이터 활용**
API 연동을 위해 더미 데이터를 임시적으로 사용했고 추후, 연동 후 데이터 모델을 실제 API 데이터로 교체 예정입니다.
> [Feat] 트레이더 상세보기 페이지 퍼블리싱

- app/(dashboard)/my/questions/_ui/question-card/index.tsx
- app/(dashboard)/my/questions/_ui/question-card/question-card.stories.tsx
- app/(dashboard)/my/questions/_ui/question-card/styles.module.scss
- shared/types/questions.ts
- shared/ui/label/index.tsx
- shared/ui/label/styles.module.scss
- shared/utils/format.ts
QuestionCard 컴포넌트 추가했습니다!
내용은 한 줄 이상 넘어가면 ... 처리 되는데, 제목은 일단 2줄 이상 나올 수 있게 만들어뒀습니다..! (이거 제한 정해둔게 있는지 모르겠는데 그렇게 길어질 것 같지는 않아서..?)
라벨도 관리자 페이지 등 다른 곳에서 사용되는 컴포넌트라 따로 분리해서 만들어뒀습니다!
스토리북에서 확인 가능!
> [Feat] 문의내역 QuestionCard 컴포넌트 추가

- app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/index.tsx
- app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/question-detail-card.stories.tsx
- app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/styles.module.scss
- app/(dashboard)/my/questions/_ui/question-card/card-mixins.scss
- app/(dashboard)/my/questions/_ui/question-card/index.tsx
- app/(dashboard)/my/questions/_ui/question-card/styles.module.scss
- 문의내역 상세 페이지에서 사용할 카드 컴포넌트 제작
- question과 answer로 구분되어있음
- QuestionCard와 공통되는 Props와 스타일을 import해서 쓸 수 있도록 리팩토링
> [Feat] 문의내역 상세 카드 컴포넌트

- app/(dashboard)/strategies/[strategyId]/page.tsx
- app/(dashboard)/strategies/_ui/search-bar/_hooks/use-accordion-button.ts
- app/(dashboard)/strategies/_ui/search-bar/_hooks/use-accordion-context.ts
- app/(dashboard)/strategies/_ui/search-bar/_store/use-searching-item-store.ts
- app/(dashboard)/strategies/_ui/search-bar/_type/search.ts
- app/(dashboard)/strategies/_ui/search-bar/_utils/type-validate.ts
- app/(dashboard)/strategies/_ui/search-bar/accordion-button.tsx
- app/(dashboard)/strategies/_ui/search-bar/accordion-container.tsx
- app/(dashboard)/strategies/_ui/search-bar/accordion-panel.tsx
- app/(dashboard)/strategies/_ui/search-bar/algorithm-item.tsx
- app/(dashboard)/strategies/_ui/search-bar/index.tsx
- app/(dashboard)/strategies/_ui/search-bar/range-container.tsx
- app/(dashboard)/strategies/_ui/search-bar/search-bar-tab.tsx
- app/(dashboard)/strategies/_ui/search-bar/search-bar-tap.tsx
- app/(dashboard)/strategies/_ui/search-bar/styles.module.scss
- app/(dashboard)/strategies/_ui/side-container/index.tsx
- app/(dashboard)/strategies/_ui/side-container/styles.module.scss
- app/(dashboard)/strategies/page.tsx
전략목록페이지 아코디언 형식의 검색 사이드바 추가 
- searchInput을 포함한 검색 사이드바 컨테이너 추가
- 검색바에서만 사용될 탭 컴포넌트 추가
- 컨테이너 내부(항목별 탭) 아코디언컨테이너는 아코디언 버튼, 버튼에 따라 열고닫히는 패널, 패널 내부는 버튼 또는 범위지정으로 구조가 되어있습니다.
- 컨테이너 내부(알고리즘 탭) 알고리즘 버튼
- 항목별 검색바에서 아코디언 버튼상태는 context사용
- 검색바에서 API요청시 보낼 검색어는 스토어로 관리 (탭 전환시에도 값이 유지)
- 초기화 버튼과 검색하기를 눌렀을때 잘못된 범위 ( min > max) 일때 에러메세지 띄우는 기능만 추가해두었습니다.  
- ACCORDION_MENU 중에 종목&매매 데이터는 페이지 진입시 API 요청해서 받아와야하는 데이터라 컴포넌트 내부에 위치시켜두었습니다.
> [Feat] 전략목록페이지 아코디언 형식의 검색 사이드바 추가

- app/(dashboard)/my/questions/_ui/question-card/index.tsx
- app/(dashboard)/my/questions/_ui/questions-tab-content/index.tsx
- app/(dashboard)/my/questions/_ui/questions-tab-content/styles.module.scss
- app/(dashboard)/my/questions/_ui/questions-tab/index.tsx
- app/(dashboard)/my/questions/page.module.scss
- app/(dashboard)/my/questions/page.tsx
- shared/types/questions.ts
- shared/ui/search-input/index.tsx
- shared/ui/search-input/search-input.stories.tsx
- shared/ui/search-input/styles.module.scss
문의 내역 api가 아직 작업 진행중이고 확정이 되지 않은 상태라 일단 더미데이터로 퍼블리싱만 먼저 작업했습니다!
api 나오고 나면 구조는 좀 바뀔 것 같아요...
- SearchInput의 handleSearchIconClick을 컨벤션에 맞게 on으로 시작하도록 수정해뒀습니다
> [Feat] 문의내역 페이지 퍼블리싱

- app/(dashboard)/_ui/details-side-item/index.tsx
- app/(dashboard)/_ui/details-side-item/side-item.tsx
- app/(dashboard)/_ui/strategies-item/styles.module.scss
- app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
- app/(dashboard)/strategies/[strategyId]/_api/get-analysis-chart.ts
- app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis-chart.ts
- app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-chart.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/index.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/subscriber-item/index.tsx
- app/(dashboard)/strategies/[strategyId]/_ui/subscriber-item/styles.module.scss
- app/(dashboard)/strategies/[strategyId]/page.tsx
- next.config.mjs
전략상세 조건부렌더링 및 분석차트 api 
- 전략상세 유저타입에 따라 조건부렌더링 처리 (리뷰, 구독버튼, 문의하기버튼)
- 분석 차트 api 연결하여 렌더링
- 사이드바 쪽 구독 컴포넌트 디자인 수정
분석차트 예시데이터 스토리북에서 사용 중이라 지우지않았습니다.
> [Feat] 전략상세 조건부렌더링 및 분석차트 api 

- app/(landing)/(home)/_api/top-strategies.ts
- app/(landing)/(home)/_hooks/query/use-get-top-ranking-smscore.ts
- app/(landing)/(home)/_hooks/query/use-get-top-ranking.ts
- app/(landing)/(home)/_ui/top-favorite-section/index.tsx
- app/(landing)/(home)/_ui/top-sm-score-section/index.tsx
- next.config.mjs
- shared/types/strategy-data.ts
구독 상위 목록 및 sm 스코어 상위 목록 api 연결했습니다!
나머지는 아직 안나옴...
> [Feat] 랜딩페이지 구독 상위 목록 및 sm 스코어 상위 목록 api 연결

- shared/utils/with-suspense.tsx
> 제곧내
상위요소에서 Suspense로 감싸기보다 각 컴포넌트 내부에서 로직을 처리하는 것이 더 응집도가 높고, 추후 보수에서도 효과적이라고 생각해서  도입하게 됐습니다.
```
// 컴포넌트.tsx
export default withSuspense(컴포넌트 이름, fallback UI)
```
> [Feat] suspense를 씌워주는 HOC 추가

- shared/ui/tabs/index.tsx
1. 기존에는 tabs 컴포넌트가 tabs 속성 내에 content를 받아 랜더링하는 역할도 수행했습니다. 이 때, 동일한 컴포넌트에 대해 데이터만 다르게 전달하는 경우 불필요하게 구조가 복잡해지는 문제가 있었습니다.
예를 들어, 컨테이너 컴포넌트에서 유저 전체 정보를 받고, 유저의 role을 기준으로 데이터를 filter 후 tab에 맞춰 랜더링할 때,
content로 컴포넌트를 넘기는 경우 각 경우에 대해 content를 넘겨야합니다. 반면 컨테이너 컴포넌트에서 state로 관리한다면 컴포넌트는 하나로 해결 가능합니다. 즉 다음과 같습니다.
```tsx
const [user, set...] = useState( )
const [tab, set...] = useState( )
// 기존
<Tabs
tabs={tabs.map((tab) => ({
id: tab,
label: tab,
content: <UserList data={ tab를 통해 구한 각 텝에 필요한 데이터 } 
}))}
activeTab={tabs[0]}
onTabChange={(id) => alert(id)}
/>
// 변경 후
<Tabs
tabs={tabs.map((tab) => ({
id: tab,
label: tab,
}))}
activeTab={tabs[0]}
onTabChange={(id) => alert(id)}
/>
<UserList data={ state를 통해 구한 각 텝에 필요한 데이터 }
```
2. 사용하는 컴포넌트에서 onChange로 콜백 함수를 넘길 때, 인자로 리터럴 타입이 넘어가면 setState에 as를 통해 …
> [Refactor] tab 컴포넌트가 content를 선택적으로 받도록 수정 및 onChange type 개선

- app/loading.module.scss
- app/loading.tsx
- shared/styles/base/_mixins.scss
- shared/ui/spinner/index.tsx
- shared/ui/spinner/styles.module.scss
로딩 페이지 추가
spinner 컴포넌트 추가
스켈레톤 mixin 추가
- 진이님이 전달해주신 lottie 파일에 문제가 있어서 일단 css로 로딩 스피너 만들어서 사용하기로 했습니다!
> [Feat] 로딩 페이지 및 스켈레톤 mixin 추가

- app/(dashboard)/_ui/details-side-item/side-item.tsx
- app/(dashboard)/_ui/strategies-item/index.tsx
- shared/ui/table/statistics/index.tsx
- shared/ui/table/vertical/index.tsx
- shared/utils/format.ts
number type 문자로 포맷 
- number type 문자로 포맷 utill 함수 추가 (number[] 인 데이터도 고려하여 두개로 나눠서 추가함)
- 일부 코드에 적용
정수 4자리수 이상의 숫자만 포맷하도록 하고 아닌 것은 원래 데이터 return 하도록 적용 
> [Feat] number type 문자로 포맷 

- app/(landing)/(home)/_ui/average-metrics-section/average-metrics-chart.tsx
- app/(landing)/(home)/_ui/average-metrics-section/index.tsx
- app/(landing)/(home)/_ui/average-metrics-section/styles.module.scss
- app/(landing)/(home)/_ui/hero-section/index.tsx
- app/(landing)/(home)/_ui/hero-section/styles.module.scss
- app/(landing)/(home)/_ui/top-favorite-section/styles.module.scss
- app/(landing)/(home)/_ui/top-sm-score-section/styles.module.scss
- app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
- shared/styles/base/_mixins.scss
모바일에서도 모든 내용을 볼 수 있을 정도로만 수정해두었습니다!
> [Design] 랜딩 페이지 반응형 스타일 적용

- shared/types/response.ts
API response에 항상 다음과 같은 값이 있어서 기저 타입을 만들어서 추가했습니다.
```ts
export interface APIResponseBaseModel<T extends boolean> {
isSuccess: T
message: string
code: T extends false ? number : never
}
```
간단히 설명하자면, isSuccess는 boolean타입이고,  isSuccess가 false인 경우에만 code속성이 존재하는 타입입니다.
```ts
export interface PresignedUrlResponseModel extends APIResponseBaseModel<boolean> {
// APIResponseBaseModel에 없는 속성에 대해서만 작성
result: {
presignedUrl: string
}
```
> [Utils] API response base interface 추가

- shared/ui/table/statistics/constant.ts
- shared/ui/table/statistics/index.tsx
전략 통계 %,일 수치 표시 추가
전략 통계 %,일 수치 표시 추가
> [Feat] 전략 통계 "%", "일" 수치 표시 추가

- app/(dashboard)/_ui/strategies-item/index.tsx
- app/(dashboard)/_ui/strategies-item/subscribe.tsx
- shared/hooks/custom/use-modal.ts
- shared/ui/modal/subscribe-warning-modal.tsx
나의 전략일때 구독 할 수 없는 경고 모달 적용
- 나의 전략일때 구독 할 수 없는 경고 모달 적용
- 커스텀 훅 closeModal 핸들러에 이벤트 전파되서 preventDefault 적용 (페이지 이동됨..)
> [Feat] 나의 전략일때 구독 할 수 없는 경고 모달 적용

- app/(dashboard)/_ui/strategies-item/skeleton/index.tsx
- app/(dashboard)/_ui/strategies-item/skeleton/styles.module.scss
- app/(dashboard)/strategies/_ui/search-bar/search-bar-skeleton/index.tsx
- app/(dashboard)/strategies/_ui/search-bar/search-bar-skeleton/styles.module.scss
- app/(dashboard)/strategies/_ui/strategy-list/index.tsx
- app/(dashboard)/strategies/loading.tsx
- app/(dashboard)/strategies/page.module.scss
- app/(dashboard)/strategies/page.tsx
전략목록 스켈레톤 ui 추가 및 적용 
전략목록 스켈레톤 ui 추가 및 적용 
-strategy-list컴포넌트에서 list헤더 page.tsx로 옮기고 suspence로 로딩 시 스켈레톤ui보여짐.
-마이페이지에서도 strategy-list컴포넌트 쓰여서 해석님께 해당 내용 전달 완료!
> [Feat] 전략목록 스켈레톤 ui 추가 및 적용 

- app/(dashboard)/_ui/details-side-item/side-skeleton/index.tsx
- app/(dashboard)/_ui/details-side-item/side-skeleton/styles.module.scss
- app/(dashboard)/strategies/[strategyId]/loading.module.scss
- app/(dashboard)/strategies/[strategyId]/loading.tsx
- app/(dashboard)/strategies/[strategyId]/page.tsx
전략 상세 로딩 스켈레톤 추가 및 적용
- 전략목록과 다르게 전략상세는 클라이언트컴포넌트로 되어있어 suspense fallback ui가 잘 보이도록 skeleton컴포넌트는 Next/dynamic, 하위 컴포넌트는 React.lazy import를 사용하여  적용했습니다. -> (복습 필요^^..)
> [Feat] 전략 상세 로딩 스켈레톤 추가 및 적용

- app/(dashboard)/_ui/analysis-container/analysis-content.tsx
- app/(dashboard)/_ui/analysis-container/statistics-content.tsx
- app/(dashboard)/_ui/analysis-container/styles.module.scss
- app/(dashboard)/_ui/details-information/styles.module.scss
- app/(dashboard)/my/_hooks/query/use-get-my-daily-analysis.ts
- app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis.ts
분석 탭에 데이터 없을 경우 ui 통일하여 추가
- 분석 탭에 데이터 없을 경우 ui 통일하여 추가
- 쿼리키 Page 누락되어 데이터 캐시되서 요청이 안되고있었음 -> 해결
> [Feat] 분석 탭에 데이터 없을 경우 ui 통일하여 추가

- app/(dashboard)/_ui/strategies-item/index.tsx
- app/(dashboard)/_ui/strategies-item/styles.module.scss
- app/(dashboard)/_ui/strategies-item/subscribe.tsx
- shared/hooks/custom/use-modal.ts
- shared/ui/modal/account-image-modal.tsx
- shared/ui/modal/signin-check-modal.tsx
- shared/ui/modal/styles.module.scss
로그인 아닐경우, 전략목록에서 리스트 클릭시 로그인체크 모달 띄우기
로그인 아닐경우, 전략목록에서 리스트 클릭시 로그인체크 모달 띄우기
-리스트 버튼 내부에 구독 버튼이 있어 이벤트 버블링 전파 방지, 이벤트 취소 적용했습니다.
> [Feat] 로그인 아닐경우, 전략목록에서 리스트 클릭시 로그인체크 모달 띄우기
