FC-DEV-FinalProject/FinalProject_team3_FE

.github/workflows/chromatic.yml

PR이 열릴 때 storybook이 배포되는 workflow를 추가했습니다. ✨

[settings] Storybook 배포 설정

---

shared/styles/base/_mixins.scss

figma의 typo들 mixin으로 옮겼습니다.
```/shared/styles/base/_mixin```에 typo들을 추가했습니다.
임의로 이름을 ```typo-h1```, ```typo-b1``` 이런 식으로 설정했는데, 더 좋은 아이디어가 있다면 추천주십쇼

[settings] typescale mixin들 추가 

---

shared/constants/path.ts
shared/ui/side-navigation/nav-link-item.tsx
shared/ui/side-navigation/styles.module.scss

라우트 폴더에 page 파일 넣고 네비게이션 테스트하다가 발견한 오류를 수정했습니다.
- 사이드 네비게이션 근처에서도 hover 효과가 일어나는 오류 수정
- 경로 오류 (PROFILE, MY_QUESTION) 수정
- my/profile 페이지에서는 active 되지 않게 수정

[Bug] 사이드 네비게이션 오류 수정

---

app/(dashboard)/my/favorites/page.tsx
app/(dashboard)/my/profile/page.tsx
app/(dashboard)/my/questions/page.tsx
app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
app/(dashboard)/my/strategies/page.tsx
app/(dashboard)/strategies/[strategyId]/page.tsx
app/(dashboard)/traders/[traderId]/page.tsx
app/(dashboard)/traders/page.tsx
app/(landing)/(home)/page.tsx
app/(landing)/signin/page.tsx
app/admin/category/page.tsx
app/admin/notices/page.tsx
app/admin/questions/page.tsx
app/admin/strategies/page.tsx

- 각 라우트 폴더에 page.tsx 파일 추가해뒀습니다
- 수민님이 추가해주신 signup 관련 페이지 파일은 제외했습니다!
- 혹시 컴포넌트명 잘못된 부분 있거나 빠진 파일 있으면 알려주세요!

[Feat] 각 라우트 폴더에 page.tsx 파일 추가

---

shared/ui/tabs/index.tsx
shared/ui/tabs/styles.module.scss
shared/ui/tabs/tab-button.tsx
shared/ui/tabs/tabs.stories.tsx

Tabs 컴포넌트 작업했습니다!
- Tabs 컴포넌트 추가
- 스토리북에 Tabs 컴포넌트 추가

[Feat] Tabs 컴포넌트 추가

---

public/icons/profile.svg
shared/ui/avatar/avatar.stories.tsx
shared/ui/avatar/index.tsx
shared/ui/avatar/styles.module.scss

아바타 컴포넌트 추가 및 스토리북에도 적용해뒀습니다!
- img url이 없을땐 기본 아이콘 출력
- 올바르지 않은 url일 경우에도 기본 아이콘 출력

[Feat] 아바타 컴포넌트 추가

---

app/(dashboard)/layout.tsx
app/(landing)/layout.tsx
app/(landing)/signup/_ui/step/styles.module.scss
app/admin/layout.tsx
shared/styles/base/_reset.scss
shared/styles/base/_variables.scss
shared/styles/global.scss
shared/ui/side-navigation/styles.module.scss

layout padding, margin 등 기본적인 main 태그 스타일을 추가해뒀습니다! (Header 고정 고려해서 작업!)
- landing layout에 그라데이션 추가

[Design] 페이지 레이아웃 공통 스타일 추가

---

shared/ui/input/index.tsx
shared/ui/input/styles.module.scss
shared/ui/search-input/index.tsx
shared/ui/search-input/styles.module.scss
shared/ui/textarea/index.tsx
shared/ui/textarea/styles.module.scss

`search-input` 아이콘 크기 관련 수정과 `input`, `search-input`, `textarea` 컴포넌트의 기능 연결 작업을 진행
**아이콘 크기 수정:** `search-input`에 포함된 아이콘의 크기를 설정
**컴포넌트 로직 개선:** `input`, `search-input`, `textarea` 컴포넌트의 입력 필드(value와 onChange)가 외부로부터 값과 이벤트를 제대로 수신할 수 있도록 연결
**인풋 색상 변경:** `input`의 색상 디자인 변경으로 SCSS 색상 수정
`value`와 `onChange` 동작 예시
```ts
'use client'
import { ChangeEvent, useState } from 'react'
import { Input } from '@/shared/ui/input'
const Test = () => {
const [value, setValue] = useState('')
const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
setValue(e.target.value)
}
return (
<>
<Input value={value} onChange={handleInputChange} />
</>
)
}
export default Test
```

[Refactor] Input 아이콘 크기 지정 및 로직 추가

---

app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-reviews-data.ts
app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
app/(dashboard)/strategies/[strategyId]/_ui/star-rating/index.tsx
app/(dashboard)/strategies/[strategyId]/_ui/star-rating/star-rating.stories.tsx
app/(dashboard)/strategies/[strategyId]/page.tsx
app/(dashboard)/strategies/_hooks/query/use-get-strategies-data.ts
mocks/handlers/strategy-details.ts
shared/ui/textarea/index.tsx
shared/ui/total-star/index.tsx
shared/ui/total-star/styles.module.scss

리뷰 컴포넌트 
- 리뷰 컴포넌트
- totalstar컴포넌트 medium fontsize수정
- details-information관련 api, query 전략상세폴더 하위로 이동
- API명세서 기반 msw 목킹 추가 및 api요청 함수, query 적용
- Textarea공통 컴포넌트 엘리먼트에 접근하여 ref current값을 알기 위해 forwardRef 적용
- starRating컴포넌트 상태 props로 전달받도록 수정
- 경로 관련 리뷰를 적지않게 받은 것 같아 2뎁스 넘어가는 것은 절대경로로 적용하도록 하겠습니다! (자동완성에 너무 익숙해져있는 것 같네요ㅠ)

[Feat] 리뷰 컴포넌트 

---

app/(dashboard)/_ui/details-information/index.tsx
app/(dashboard)/_ui/strategies-item/area-chart.tsx
app/(dashboard)/_ui/strategies-item/index.tsx
app/(dashboard)/_ui/strategies-item/strategies-item.stories.tsx
app/(dashboard)/my/_api/get-favorite-strategy-list.ts
app/(dashboard)/my/_api/get-my-strategy-list.ts
app/(dashboard)/my/_hooks/query/use-get-my-strategy-list.ts
app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-reviews-data.ts
app/(dashboard)/strategies/[strategyId]/_ui/analysis-container/analysis-content.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
app/(dashboard)/strategies/[strategyId]/page.tsx
app/(dashboard)/strategies/_api/get-strategies.ts
app/(dashboard)/strategies/_ui/strategy-list/index.tsx
mocks/handlers/strategies.ts
mocks/handlers/strategy-details.ts
shared/hooks/custom/use-pagination.ts
shared/types/strategy-data.ts
shared/ui/table/vertical/index.tsx

전략 API 수정 이슈로 인한 관련 로직 수정
- 타입 파일명 수정
- api request 형식에 맞춰 목데이터, props, 타입 수정
- 그 외 경로 수정

[Refactor] 전략 API 수정 이슈로 인한 관련 로직 수정

---

app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
app/(dashboard)/my/questions/[questionId]/_ui/question-container/styles.module.scss
shared/ui/textarea/styles.module.scss

트레이더일 때 답변하기 textarea를 띄워주는 부분 퍼블리싱 작업 진행했습니다!

[Feat] 답변하기 textarea 추가 퍼블리싱

---

app/(dashboard)/strategies/_ui/strategy-list/index.tsx
app/(landing)/signup/information/page.tsx
shared/ui/modal/index.tsx
shared/ui/modal/modal.stories.tsx
shared/ui/modal/signin-check-modal.tsx
shared/ui/modal/styles.module.scss
shared/ui/modal/subscribe-check-modal.tsx

[Feat] 로그인, 구독 모달 추가

---

app/(dashboard)/_ui/details-information/index.tsx
app/(dashboard)/_ui/strategies-item/index.tsx
app/(dashboard)/_ui/strategies-item/subscribe.tsx
app/(dashboard)/_ui/subscriber-item/index.tsx
app/(dashboard)/strategies/[strategyId]/_api/get-analysis-chart.ts
app/(dashboard)/strategies/[strategyId]/_api/get-analysis.ts
app/(dashboard)/strategies/[strategyId]/_api/get-details-information.ts
app/(dashboard)/strategies/[strategyId]/_api/get-reviews.ts
app/(dashboard)/strategies/[strategyId]/_api/get-statistics.ts
app/(dashboard)/strategies/[strategyId]/_api/post-review.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-details-information-data.ts
app/(dashboard)/strategies/[strategyId]/page.tsx
app/(dashboard)/strategies/_api/get-subscribe.ts
app/(dashboard)/strategies/_hooks/query/use-get-subscribe.ts

구독 api & 확인 모달 적용
구독 api 추가, 로그인여부 및 구독 확인 모달 적용

[Feat] 구독 api & 확인 모달 적용

---

shared/ui/footer/styles.module.scss

Footer도 모바일에서 내용 깨지지 않게 보일 정도로만 수정해두었습니다!

[Design] footer 반응형 디자인 적용

---

app/(landing)/(home)/_ui/hero-section/index.tsx

[Fix] 랜딩 페이지 바로 함께하기 버튼 조건 처리

---

app/(dashboard)/_ui/list-header/styles.module.scss
app/(dashboard)/_ui/strategies-item/styles.module.scss
app/(dashboard)/strategies/_api/get-strategies-search.ts
app/(dashboard)/strategies/_api/get-subscribe.ts
app/(dashboard)/strategies/_api/post-strategies.ts
app/(dashboard)/strategies/_ui/search-bar/_store/use-searching-item-store.ts
app/(dashboard)/strategies/_ui/search-bar/index.tsx
app/(dashboard)/strategies/_ui/strategy-list/index.tsx

검색바 호출 버그 개선 및 목록 디자인 그리드사이즈 수정
- 검색바 호출 버그 개선 및 목록 디자인 그리드사이즈 수정
- axiosInstance로 수정

[Bug] 검색바 호출 버그 개선 및 목록 디자인 그리드사이즈 수정

---

shared/ui/header/index.tsx
shared/ui/header/styles.module.scss

모바일에서도 헤더 볼 수 있게 햄버거메뉴 추가했습니다!

[Design] 헤더 반응형 작업

---

app/(landing)/privacy-terms/page.module.scss
app/(landing)/terms-of-use/page.module.scss
app/(landing)/terms-of-use/page.tsx

피그마 디자인에 추가해주신 여백, 폰트 사이즈 지정해서 스타일 수정했습니다!

[Design] 약관 페이지 여백 추가 및 폰트 사이즈 수정

---

app/(landing)/(home)/_api/strategies-metrics.ts
app/(landing)/(home)/_hooks/query/use-get-strategies-metrics.ts
app/(landing)/(home)/_ui/average-metrics-section/average-metrics-chart.tsx
app/(landing)/(home)/_ui/average-metrics-section/index.tsx

[Feat] 대표 전략 통합 평균 지표 api 연결

---

app/(dashboard)/strategies/[strategyId]/_api/delete-review.ts
app/(dashboard)/strategies/[strategyId]/_api/patch-review.ts
app/(dashboard)/strategies/[strategyId]/_api/post-review.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-delete-review.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-patch-review.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-post-review.ts
app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/index.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-guide-modal.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-list.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/styles.module.scss
app/(dashboard)/strategies/_ui/search-bar/range-container.tsx

리뷰 수정, 삭제 api 추가 & 안내모달 적용 
- 리뷰 수정 삭제 api 추가 및 적용
- 이미등록된 리뷰가 있으면 안내모달 오픈
- 리뷰 삭제할때 재확인 안내모달 오픈

[Feat] 리뷰 수정, 삭제 api 추가 & 안내모달 적용 

---

app/(landing)/notices/_ui/notice-table/index.tsx
app/(landing)/notices/_ui/notice-table/styles.module.scss
app/(landing)/notices/page.module.scss
app/(landing)/notices/page.tsx
shared/ui/table/vertical/index.tsx

공지사항 페이지 퍼블리싱 작업했습니다
목데이터 넣어뒀어요!

[Feat] 공지사항 페이지 퍼블리싱

---

app/(dashboard)/_ui/analysis-container/analysis-chart.tsx
app/(dashboard)/_ui/analysis-container/styles.module.scss
app/(dashboard)/_ui/details-information/index.tsx
app/(dashboard)/_ui/strategies-item/area-chart.tsx
app/(dashboard)/_ui/strategies-item/index.tsx
app/(dashboard)/_ui/strategies-item/strategies-icon.tsx
app/(dashboard)/_ui/strategies-item/styles.module.scss
app/(dashboard)/strategies/_api/get-subscribe.ts
shared/ui/total-star/index.tsx
shared/ui/total-star/styles.module.scss

종목매매 아이콘 주석해제, 예외처리 추가 및 일부 스타일수정
- 이미지 예외처리 추가
- 차트 예외처리 추가
- 구독 api수정되어 쿼리마라미터에 userId 제거
- strategies-item에 total-star와 겹치는 스타일이 있어 스타일 정리

[Bug] 종목매매 아이콘 주석해제, 예외처리 추가 및 일부 스타일수정

---

app/(dashboard)/_ui/details-side-item/index.tsx
app/(dashboard)/_ui/details-side-item/side-item.tsx
app/(dashboard)/strategies/[strategyId]/page.tsx
shared/ui/input/styles.module.scss
shared/ui/modal/add-question-modal.tsx
shared/ui/modal/question-guide-modal.tsx
shared/ui/modal/styles.module.scss

문의하기 모달 & 문의 등록 성공 안내 모달 추가
- Input컴포넌트 border 색상이 디자인과 달라서 수정
- 문의하기 모달 추가
- 문의 등록 성공 안내모달 추가
- 문의 제목,내용 빈값일때 에러문구 적용
- 전략상세 "문의하기" 버튼에 적용
- api 아직 안나와서 TODO 주석 달아둠

[Feat] 문의하기 모달 & 문의 등록 성공 안내 모달 추가

---

app/(dashboard)/_ui/details-side-item/side-item.tsx
app/(dashboard)/_ui/strategies-item/subscribe.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/add-review.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-guide-modal.tsx
app/(dashboard)/strategies/[strategyId]/_ui/review-container/review-item.tsx
app/(dashboard)/strategies/[strategyId]/page.tsx
shared/ui/modal/add-question-modal.tsx
shared/ui/modal/question-guide-modal.tsx
shared/ui/modal/signin-check-modal.tsx
shared/ui/modal/subscribe-check-modal.tsx

모달 핸들러 함수명 수정
모달 핸들러 함수명 'on' 명시

[Refactor] 모달 핸들러 함수명 수정

---

app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/question-detail-card.stories.tsx
app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/styles.module.scss
app/(dashboard)/my/questions/_api/get-my-question-list.ts
app/(dashboard)/my/questions/_api/get-question-details.ts
app/(dashboard)/my/questions/_hooks/query/use-get-my-question-list.ts
app/(dashboard)/my/questions/_hooks/query/use-get-question-details.ts
app/(dashboard)/my/questions/_ui/question-card/index.tsx
app/(dashboard)/my/questions/_ui/question-card/question-card.stories.tsx
app/(dashboard)/my/questions/_ui/questions-tab-content/index.tsx
app/(dashboard)/my/questions/_ui/questions-tab/index.tsx
app/(dashboard)/my/questions/page.tsx
shared/types/questions.ts

- 문의 내역 및 문의 내역 상세 불러오기 api 연결했습니다!

[Feat] 문의 내역 불러오기 api 연결

---

app/(dashboard)/_ui/details-side-item/details-side-item.stories.tsx
app/(dashboard)/_ui/details-side-item/index.tsx
app/(dashboard)/_ui/details-side-item/side-item.tsx
app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
app/(dashboard)/strategies/[strategyId]/_api/post-question.ts
app/(dashboard)/strategies/[strategyId]/_hooks/query/use-post-question.ts
app/(dashboard)/strategies/[strategyId]/page.tsx

문의 등록 api 추가 및 적용
문의 등록 api 추가 및 적용

[Feat] 문의 등록 api 추가 및 적용

---

app/(dashboard)/my/profile/_ui/user-info/index.tsx
app/(dashboard)/my/profile/_ui/user-info/styles.module.scss
app/(dashboard)/my/profile/_ui/user-profile/index.tsx
app/(dashboard)/my/profile/_ui/user-profile/styles.module.scss
app/(dashboard)/my/profile/page.module.scss
app/(dashboard)/my/profile/page.tsx
shared/constants/path.ts

마이페이지 프로필페이지 퍼블리싱을 진행하고 PATH에 경로를 추가했습니다!

[Feat] 마이페이지 프로필페이지 퍼블리싱

---

app/(dashboard)/strategies/[strategyId]/_hooks/query/use-get-analysis.ts

전략 분석 api 쿼리키 추가 
전략 일간/월간 분석 type에 따라 api 요청했는데 쿼리키에 type누락으로 캐시되서 요청이 되지 않아 추가했습니다.

[HotFix] 전략 분석 api 쿼리키 추가 

---

app/(landing)/(home)/_api/user-metrics.ts
app/(landing)/(home)/_hooks/query/use-get-user-metrics.ts
app/(landing)/(home)/_ui/user-metrics-section/index.tsx
app/(landing)/(home)/types.ts

[Feat] 랜딩 페이지 사용자 지표 api 연동

---

app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
app/(dashboard)/my/questions/_api/post-answer.ts
app/(dashboard)/my/questions/_hooks/query/use-post-answer.ts
app/(dashboard)/my/questions/_ui/questions-tab/index.tsx
shared/types/questions.ts

- 문의 상세 페이지에서 트레이더가 답변을 달 수 있는 기능을 추가했습니다

[Feat] 문의 답변 등록 기능 구현

---

app/(dashboard)/_ui/details-side-item/side-item.tsx
app/(dashboard)/my/questions/[questionId]/_ui/question-container/index.tsx
app/(dashboard)/my/questions/[questionId]/_ui/question-detail-card/index.tsx
app/(dashboard)/my/questions/_api/delete-answer.ts
app/(dashboard)/my/questions/_api/delete-question.ts
app/(dashboard)/my/questions/_hooks/query/use-delete-answer.ts
app/(dashboard)/my/questions/_hooks/query/use-delete-question.ts
app/(dashboard)/my/questions/_ui/answer-delete-modal/index.tsx
app/(dashboard)/my/questions/_ui/answer-delete-modal/styles.module.scss
app/(dashboard)/my/questions/_ui/modal/question-delete-modal.tsx
app/(dashboard)/my/questions/_ui/modal/styles.module.scss
shared/types/questions.ts
shared/ui/modal/add-question-modal.tsx

- 문의 내역 삭제 기능 구현
- 답변 삭제 기능 구현
- 추가 문의하기 기능 구현
원래 추가 문의하기는 따로 PR 올리려고 했는데.. api 수정 기다리는김에 같이 했습니다..!
- 문의하기 모달 같이 사용하기 편하게 수정했습니다!

[Feat] 문의내역, 답변 삭제 및 추가 문의하기 기능 구현

---

app/(landing)/(home)/_ui/user-metrics-section/index.tsx
app/(landing)/(home)/_ui/user-metrics-section/styles.module.scss
shared/ui/spinner/index.tsx
shared/ui/spinner/styles.module.scss

스켈레톤 디자인이 없는 곳 등 스피너가 필요한 곳에서 사용할 때 가운데 정렬되도록 수정했습니다!

[Feat] Spinner 가운데 정렬

---

app/(dashboard)/my/favorites/_ui/favorite-strategy-list/index.tsx
app/(dashboard)/my/favorites/_ui/favorite-strategy-list/styles.module.scss
app/(dashboard)/my/favorites/page.tsx

구독한 전략이 없을때 문구 추가 및 스켈레톤 UI 적용해두었습니다

[Feat] 구독한 전략 없을때 문구 및 스켈레톤 UI 적용

---

app/(landing)/signup/complete/page.tsx

회원가입 완료 메시지가 바로 뜨지 않는 오류 해결했습니다
누가 회원가입 테스트좀..

[Bug] 회원가입 완료 메시지가 바로 뜨지 않는 오류 해결

---

app/(dashboard)/my/strategies/manage/[strategyId]/page.tsx
app/(dashboard)/strategies/[strategyId]/page.tsx
shared/ui/modal/subscribe-check-modal.tsx

params 수정
- params string타입으로 수정
- 구독모달 핸들러 수정

[Fix] params수정

---

app/(dashboard)/_ui/details-side-item/side-item.tsx
app/(dashboard)/_ui/details-side-item/styles.module.scss

내전략일때 전략관리페이지로 이동버튼 추가 (마페에서는 안보이게해둠)

[Feat] 내전략일때 전략관리페이지로 이동버튼 추가

---

app/(dashboard)/my/_api/get-profile.ts
app/(dashboard)/my/_hooks/query/use-get-profile.ts
app/(dashboard)/my/profile/_ui/user-info/index.tsx
app/(dashboard)/my/profile/_ui/user-info/types.ts
app/(dashboard)/my/profile/_ui/user-info/utils.ts
app/(dashboard)/my/profile/edit/page.tsx
app/(dashboard)/my/profile/page.tsx
app/(landing)/notices/[noticeId]/detail/page.tsx
app/(landing)/notices/_api/get-notice-detail.ts
app/(landing)/notices/_hooks/use-notice-detail.ts
app/(landing)/notices/_ui/notice-detail/index.tsx
shared/utils/validation.ts

PR이긴한데 사실상 Help 요청입니다.. 이렇게 하는거 맞나요...?

[Feat] 프로필 get요청, 공지사항 상세보기 get 요청 API 연동

---

app/admin/users/_ui/user-delete-button.tsx
app/admin/users/page.tsx

유저 강제 탈퇴시키는 api까지 연동하여 관리자의 유저 페이지를 마무리했습니다.

feat: 관리자 사용자 페이지 완성

---

app/(dashboard)/_ui/strategies-item/strategies-icon.tsx
app/(dashboard)/_ui/strategies-item/styles.module.scss

아이콘 사이즈 배율에 맞게 수정
- 2배율로 업로드 하셨다고 해서 아이콘 사이즈 배율에 맞게 수정했습니다.

[Fix] 아이콘 사이즈 배율에 맞게 수정
